import type { Metadata } from "next";
import { Michroma } from "next/font/google";
import "./globals.css";

const michroma = Michroma({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Jox-Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" selection:bg-primary/70">
      <body className={`${michroma.className}`}>{children}</body>
    </html>
  );
}
