import type { Metadata } from "next";
import { Michroma } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import MouseGlowEffect from "@/components/MouseGlowEffect";
import LoadingScreen from "@/components/LoadingScreen";
import Navbar from "@/components/Navbar";
const michroma = Michroma({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jox-Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={cn(
          "bg-gray-900 text-white min-h-screen antialiased",
          michroma.className
        )}
      >
        <Navbar />
        <MouseGlowEffect />
        <LoadingScreen />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
